---
- name: Activity playbook
  hosts: webservers
  become: true
  tasks:

          - name: download filebeat .deb
            apt:
                    deb: https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-7.4.0-amd64.deb

          - name: copy config file
            ansible.builtin.copy:
                    src: /etc/ansible/roles/files/filebeat-config.yml
                    dest: /etc/filebeat/filebeat.yml

          - name: filebeat modules
            command: filebeat modules enable system

          - name: setup filebeat
            command: filebeat setup

          - name: start filebeat service
            command: service filebeat start

          - name: enable filebeat
            systemd:
                    name: filebeat
                    enabled: yes
