---
- name: Activity playbook
  hosts: webservers
  become: true
  tasks:

          - name: download metricbeat .deb
            apt:
                    deb: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-7.4.0-amd64.deb

          - name: copy config file
            ansible.builtin.copy:
                    src: /etc/ansible/roles/files/metricbeat-config.yml
                    dest: /etc/metricbeat/metricbeat.yml

          - name: metricbeat modules
            command: metricbeat modules enable docker

          - name: setup metricbeat
            command: metricbeat setup

          - name: start metricbeat service
            command: service metricbeat start

          - name: enable metricbeat
            systemd:
                    name: metricbeat
                    enabled: yes
